### ISSUE TITLE
Wallpaper also getting tiled.

### ISSUE THREAD

**Issue by Vaisakhkm2625** [zeroxoneafour/kwin-autotile#23] opened 2023-05-10 15:28 UTC
i am not sure whether it is a bug in kde plasma itself, or this extension, but sometimes the focus goes from window to wallpaper itself, the wallpaper also getting tilied, 

after that i has to use kde with a mouse otherwise wallpaper stating to take half of the window..... or i have restart system...

![wallpaperautotile](https://github.com/zeroxoneafour/kwin-autotile/assets/68694876/a2015ab5-d6a4-40d9-9ad9-e6c64f560bb1)

i am not sure where to get logs, please ask me if needed any extra information/guide me to get....

Thanks for making this extention... i have been using this for few months now.... hopfully kde will improve tiling capabilities in kde6

**Comment by zeroxoneafour** [comment] 2023-05-10 17:10
In the faq.md file on the GitHub, you can find instructions on how to make a log. If you can upload that it would be very helpful.

Also make sure that you're running 1.2 and not 1.3. You can check this in the kwin script settings.

**Comment by zeroxoneafour** [comment] 2023-05-10 17:10
In the faq.md file on the GitHub, you can find instructions on how to make a log. If you can upload that it would be very helpful.

Also make sure that you're running 1.2 and not 1.3. You can check this in the kwin script settings.

**Comment by Vaisakhkm2625** [comment] 2023-05-11 18:20
I followed the FAQ, but i wasn't able to get any output...

```
⚡➜ ~ journalctl --user --no-pager -e | grep "Autotile"
⚡➜ ~ journalctl --user --no-pager -e | grep "autotile"
⚡➜ ~ journalctl --user --no-pager -e | wc             
    466   11119  107744
⚡➜ ~ 
```

i enabled debug mode in script settings

**Comment by zeroxoneafour** [comment] 2023-05-11 18:53
Pressing the tile window shortcut may tile the background window if it is the currently selected window. Does it autotile or only tile then?

**Comment by Vaisakhkm2625** [comment] 2023-05-12 00:29
It's tile the wallpaper... along with autotiled windows.... like if i open more windows, it gets tiled alone with it...

**Comment by Vaisakhkm2625** [comment] 2023-05-12 01:23
https://github.com/zeroxoneafour/kwin-autotile/assets/68694876/d88a4b9b-b3b2-4b12-a54a-6383f8619479

**Comment by zeroxoneafour** [comment] 2023-05-12 04:54
This is intentional behavior. Kwin treats the desktop like a window and, although the script has guards in place to stop it from automatically tiling, it will not stop you from tiling it yourself if you do by selecting it and pressing the shortcut.

If it doesn't return to its normal untiled position after pressing the shortcut again with the desktop window selected, then that is a bug.

**Comment by Vaisakhkm2625** [comment] 2023-05-12 15:04
> This is intentional behavior. Kwin treats the desktop like a window and, although the script has guards in place to stop it from automatically tiling, it will not stop you from tiling it yourself if you do by selecting it and pressing the shortcut.
> 
> If it doesn't return to its normal untiled position after pressing the shortcut again with the desktop window selected, then that is a bug.

Thanks for clarification. 

it is *untiling*, but just becoming a normal window, not going back to the original position. (leaving black space in place of panel)..

actually the real issue is, sometimes when i presses Meta+shift+space, it is not tiling/untiling, but switch focus between windows... which sometimes focus wallpaper and make it tiling....

I used mouse for recreating the issue because that behaviors is inconsistent and mostly appears when wall paper becomes tiling.. so i assumed both are related...

**Comment by zeroxoneafour** [comment] 2023-05-13 18:09
Actually it probably isn't a bug if the window doesn't return to its old position, because Kwin doesn't store stuff like that.

Make sure that the keybinds to retile/untile and the keybinds to switch active windows are different. If they're the same, it can cause conflicts like this.

I'm going to close this issue if the cause of the problem is clear now.

**Closed by zeroxoneafour** 2023-05-13 18:09 UTC
