### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by Francesco7602** [zeroxoneafour/kwin-autotile#3] opened 2023-03-19 13:35 UTC
![immagine](https://user-images.githubusercontent.com/43477782/226178437-f5695cdc-ca35-4e07-a9ff-01cc64b6c963.png)

When i tile in another virtual desktop, sometime, on the other desktop put the window on half screen, even if there is only that window.
You can try to recreate it by open firefox in desktop 1, then switch to desktop 2 and do some tiling
Sometime everything works fine, but other time there is this strange bug.

![immagine](https://user-images.githubusercontent.com/43477782/226187350-5f41188e-7871-4e22-9212-daed7da90343.png)

Oh, and sometime the autotile don't work, like the second image

**Comment by zeroxoneafour** [comment] 2023-03-19 16:13
I want to say that some of these bugs are caused by a race condition between the geometry being changed in the windows and the desktop/status of the windows being changed. There's not a whole lot that I can do because this is internal within KWin, but I'm working on setting some flags so that geometryChange will not be triggered. In the meantime, bind the untile/retile window keybind to something in your shortcuts and you should be able to double-click it to fix most problems.

**Comment by zeroxoneafour** [comment] 2023-03-19 16:14
Also it almost goes without saying, but make sure you're using version 0.2.2. A lot of these bugs existed very, very frequently in v0.1.3 and lower.

**Comment by zeroxoneafour** [comment] 2023-03-19 20:55
v0.3.0 has some added protection against these race conditions, try it out and see if it works

**Comment by Francesco7602** [comment] 2023-03-20 09:07
Well, it look like that now works!
But, now when i create a new window it pop up at left, and the already existing window go to the right.
I don't know if is a bug or not, but is a bit strange i think

**Comment by zeroxoneafour** [comment] 2023-03-20 11:46
This is intended behavior, but I can see how some people may not like it. I'll add a switch to change the insertion order. Closing this issue because the original problem has been resolved

**Closed** 2023-03-20 11:46 UTC

**Comment by zeroxoneafour** [comment] 2023-03-20 22:43
The switch to change the insertion order has been added, so windows will now pop up on the right if you enable it in the script settings.
